"""add free_sections_count to projects

Revision ID: e3f6fb915ba3
Revises: d64684b235e4
Create Date: 2025-10-20 00:58:37.043245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3f6fb915ba3'
down_revision = 'd64684b235e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('free_sections_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('free_sections_count')

    # ### end Alembic commands ###
