"""Initial clean migration for Boost A Project

Revision ID: eee17872c641
Revises: 
Create Date: 2025-10-14 12:14:45.189177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eee17872c641'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Crear tabla users
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=80), nullable=False),
        sa.Column('email', sa.String(length=120), nullable=False),
        sa.Column('password_hash', sa.String(length=128), nullable=True),
        sa.Column('is_admin', sa.Boolean(), nullable=True),
        sa.Column('last_name', sa.String(length=80), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('username')
    )
    
    # Crear tabla articles
    op.create_table('articles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('slug', sa.String(length=250), nullable=False),
        sa.Column('excerpt', sa.Text(), nullable=True),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('image', sa.String(length=255), nullable=True),
        sa.Column('image_alt', sa.String(length=255), nullable=True),
        sa.Column('meta_description', sa.String(length=160), nullable=True),
        sa.Column('meta_keywords', sa.String(length=255), nullable=True),
        sa.Column('related', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('slug')
    )
    
    # Crear tabla projects
    op.create_table('projects',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=120), nullable=False),
        sa.Column('slug', sa.String(length=150), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('image_url', sa.String(length=255), nullable=True),
        sa.Column('investment_goal', sa.Float(), nullable=False),
        sa.Column('location', sa.String(length=120), nullable=False),
        sa.Column('investment_type', sa.String(length=100), nullable=True),
        sa.Column('surface_m2', sa.Integer(), nullable=True),
        sa.Column('rooms', sa.Integer(), nullable=True),
        sa.Column('bathrooms', sa.Integer(), nullable=True),
        sa.Column('min_investment', sa.Float(), nullable=True),
        sa.Column('expected_return', sa.String(length=10), nullable=True),
        sa.Column('optimistic_return', sa.String(length=10), nullable=True),
        sa.Column('estimated_duration', sa.String(length=50), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('financial_structure', sa.JSON(), nullable=True),
        sa.Column('risk_mitigations', sa.JSON(), nullable=True),
        sa.Column('gallery', sa.JSON(), nullable=True),
        sa.Column('financial_structure_text', sa.Text(), nullable=True),
        sa.Column('rentability_projection', sa.Text(), nullable=True),
        sa.Column('risk_analysis', sa.Text(), nullable=True),
        sa.Column('team_description', sa.Text(), nullable=True),
        sa.Column('external_link', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('slug')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    op.drop_table('articles')
    op.drop_table('users')
    # ### end Alembic commands ###
